name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true   # fetch PaperMod theme

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.162.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to VPS
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete
          path: public/
          remote_path: /var/www/qubitlogic/
          remote_host: 51.195.86.197
          remote_user: ubuntu
          remote_key: ${{ secrets.VPS_SSH_KEY }}
